### ISSUE TITLE
Config文件错误

### ISSUE THREAD

**Issue by Haibersut** [tomorinao-www/nonebot-plugin-qrcode2#2]
安装启动后报错：
```
03-15 20:15:19 [ERROR] nonebot | Failed to import "nonebot_plugin_qrcode2"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\ProgramData\miniconda3\envs\gocq\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot_plugin_qrcode2\__init__.py", line 24, in <module>
    from .config import Config
  File "C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot_plugin_qrcode2\config.py", line 1, in <module>
    from nonebot.config import BaseConfig
ImportError: cannot import name 'BaseConfig' from 'nonebot.config' (C:\ProgramData\miniconda3\envs\gocq\lib\site-packages\nonebot\config.py)
```

看了下官方文档好像没有BaseConfig这个类了，现在用的是BaseModel
https://github.com/nonebot/nonebot2/blob/fcd536aada9b5d5ae00cbd307050e505dcdd91ee/website/versioned_docs/version-2.1.3/appendices/config.mdx#L230

将
https://github.com/tomorinao-www/nonebot-plugin-qrcode2/blob/b6bb94aa121d028fe36b906c1cf29b6aaec94732/nonebot_plugin_qrcode2/config.py#L1-L4
修改为
```python
from pydantic import BaseModel


class Config(BaseModel):
```
即可

或者是我安装的方式不对（

**Comment by tomorinao-www** [comment]
感谢提醒，已更新配置
